FROM mysql:8.0

# Kopieer het SQL-bestand naar de container
COPY hive.sql /docker-entrypoint-initdb.d/hive.sql

ENV MYSQL_ROOT_PASSWORD=DitIsSQL2002
ENV MYSQL_DATABASE=hive

ENV MYSQL_PASSWORD=DitIsSQL2002

EXPOSE 3306
